name: Django Tests

on:
  push: 
    branches: 
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  ##Deployment on successful build and test###############
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy to AWS
        shell: bash
        env:
          PRIVATE_KEY : ${{ secrets.AWS_DEMOSERVERRSAKEY  }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          # echo -e "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/private.key
          echo -e "$PRIVATE_KEY" > ~/.ssh/private.key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private.key  
          touch ~/xyz
          scp -i ~/.ssh/private.key ~/xyz ubuntu@ec2-16-170-141-234.eu-north-1.compute.amazonaws.com:~
          # ssh ubuntu@ec2-16-170-141-234.eu-north-1.compute.amazonaws.com
  #################################

  
