name: Django Tests

on:
  push: 
    branches: 
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  ##Deployment on successful build and test###############
  
  #################################

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: mk_deployer
          key: ${{ secrets.AWS_DEMOSERVERRSAKEY }}
          port: 22
          script: |
            echo "Hi - welcome to EC2"
            # cd /var/www/test
            # ls -al
  ################################
  
