name: Django Tests

on:
  push: 
    branches: 
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  ##Deployment on successful build and test###############

  #################################
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set up SSH key for EC2
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.AWS_DEMOSERVERRSAKEY }}" > ~/.ssh/id_rsa.pem
        chmod 600 ~/.ssh/id_rsa.pem
        touch ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        echo "${{ secrets.IP_ADDRESS }}  ssh_rsa  ${{ secrets.AWS_DEMOSERVERRSAKEY }}" > ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: SSH into EC2 and run commands
      run: |
        # Add EC2 host to known hosts (prevent SSH prompt)
        # ssh-keyscan -H ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts
        # ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        
        # SSH into the EC2 instance and run commands
        ssh -i ~/.ssh/id_rsa.pem  mk_deployer@ec2-16-170-141-234.eu-north-1.compute.amazonaws.com 'bash -s' << 'EOF'
          # Add commands to run on EC2, like deploying your app
          echo "Logged into EC2"
        EOF
  ################################
  
