name: Django Tests

on:
  push: 
    branches: 
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with: 
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check .
    - name: Make django DB migrations
      run: |
        python3 manage.py migrate 
      
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test
  ##Deployment on successful build and test###############
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Build was successful!!"
    # runs-on: ubuntu-latest
    # name: Package
    # steps:
    #   - uses: actions/checkout@v2
    #   # your stuff

    #   # Configure AWS credentials
    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
    #   # Update the Origin Path
    #   - name: Update OriginPath
    #     uses: mean-dao/aws-webdeploy@v1
    #     with:
    #       ORIGIN_PATH: '/v1/new_path'
    #       AWS_DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}